name: TestBuild

on: [push]

permissions:
  contents: write

jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20.2
      - name: Build
        run: ./build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: ./target
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
            target/SonyVideoRename-Linux_x86_64
            target/SonyVideoRename-Linux_x86_64.sha256
            target/SonyVideoRename-Windows_x86_64.exe
            target/SonyVideoRename-Windows_x86_64.exe.sha256
            target/SonyVideoRename-macOS_x86_64
            target/SonyVideoRename-macOS_x86_64.sha256
            target/SonyVideoRename-macOS_arm
            target/SonyVideoRename-macOS_arm.sha256
  download-project:
    name: Download project
    runs-on: ubuntu-latest
    needs: build-project
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: Artifacts
    - name: Test artifact download
      run: ls -R
